mysql:
   image: cisco/mysql:5.5
   ports: 
     - "3366:3306"
   volumes:
     - /var/lib/docker/vfs/dir/dataxc:/var/lib/mysql
   hostname: db.jiadong.vm

tomcat:
   image: cisco/tomcat:7
   ports:
      - "8080:8080"
   links:
      - mysql:db
   environment:
      - TOMCAT_USER=admin
      - TOMCAT_PASS=admin
   hostname: tomcat.jiadong.vm
